version: '2'

services:

  # ---------------------------------------------
  # Web application Docker container.
  # ---------------------------------------------
  web:
    build: .
    environment:
      SECRET_KEY: 'foo-bar'
      DEBUG: 'true'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      REDIS_DB: 1
      SQLALCHEMY_DATABASE_URI: 'postgresql://sit-amet:lorem-ipsum-dolor@database:5432/consectetur'
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    depends_on:
      - 'redis'
      - 'database'

  # ---------------------------------------------
  # Redis Docker container.
  # ---------------------------------------------
  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  # ---------------------------------------------
  # PostgreSQL Docker container.
  # ---------------------------------------------
  database:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'lorem-ipsum-dolor'
      POSTGRES_USER: 'sit-amet'
      POSTGRES_DB: 'consectetur'

networks:
  altman:
